### PR TITLE
usage: only show the filename

### PR DESCRIPTION
**Pull request by 1ace**
There's no need to show the entire path, the filename is enough :)

### CODE REVIEW

**Comment by mollerhoj** [comment]
I disagree, filenames can be ambiguous for many projects.

**Comment by koreno** [comment]
Sorry for the late response...
@1ace - could you "hide" this feature behind a option flag? or an environment variable?
I do agree with @mollerhoj that the common (and worst) case requires the tool to show full path names

**Comment by 1ace** [comment]
I'm really confused, I don't think we're talking about the same thing here…

This PR is just so that the help message telling the user how to use `prebase` doesn't show the entire path to the script, it has nothing to do with what the tool does.

Passing an option to `git prebase` to not show the path to prebase itself in its "no option was passed" help message makes absolutely zero sense to me 🤷‍♀️

**Comment by koreno** [comment]
Ah right, sorry, wasn't paying close enough attention...
I thought this was about the filenames in the affected files list.

**Pull request merged**
